# GCE's zshrc
ZSH=$HOME/.oh-my-zsh

fpath=(/usr/local/share/zsh-completions $fpath)

plugins=(
    zsh-autosuggestions
    zsh-completions
    zsh-syntax-highlighting
)

autoload -U compinit && compinit

ZSH_THEME="powerlevel10k/powerlevel10k"

COMPLETION_WAITING_DOTS="true"

# Mode must be set before sourcing oh-my-zsh
POWERLEVEL9K_MODE='awesome-patched'

# START --> GCE
    POWERLEVEL9K_PROMPT_ON_NEWLINE=true
    POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

    POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
    POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
    POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
    POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''

    POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=" %n%B@%m%b"
    POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" \u276F "

    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status dir dir_writable_joined)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time vcs background_jobs_joined)

    POWERLEVEL9K_HOST_LOCAL_FOREGROUND="015"
    POWERLEVEL9K_HOST_LOCAL_BACKGROUND="clear"

    POWERLEVEL9K_HOST_REMOTE_FOREGROUND="015"
    POWERLEVEL9K_HOST_REMOTE_BACKGROUND="clear"

    POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="clear"
    POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
    POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="clear"
    POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="white"

    POWERLEVEL9K_DIR_ETC_BACKGROUND="clear"
    POWERLEVEL9K_DIR_ETC_FOREGROUND="014"
    POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"
    POWERLEVEL9K_DIR_HOME_FOREGROUND="014"
    POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"
    POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="014"
    POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"
    POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
    POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"
    POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="014"
    POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="red"
    POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="white"
    POWERLEVEL9K_STATUS_OK_BACKGROUND="clear"
    POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
    POWERLEVEL9K_STATUS_ERROR_BACKGROUND="clear"
    POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
    POWERLEVEL9K_STATUS_VERBOSE=false
    POWERLEVEL9K_TIME_BACKGROUND="clear"
    POWERLEVEL9K_TIME_FOREGROUND="120"
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='clear'
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='magenta'
    POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='clear'
    POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='green'

    POWERLEVEL9K_HOME_ICON=''
    POWERLEVEL9K_HOME_SUB_ICON=''
    POWERLEVEL9K_FOLDER_ICON=''
    POWERLEVEL9K_ETC_ICON=''

    POWERLEVEL9K_CONTEXT_TEMPLATE="%n@`hostname -f`"
# END   --> GCE

source $ZSH/oh-my-zsh.sh

bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line
bindkey  "^[^[[D" backward-word
bindkey  "^[^[[C" forward-word
